# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      -
        name: Setup Node.js (for semantic-release)
        uses: actions/setup-node@v1
        with:
          node-version: 12
      -
        name: Install npm dependencies
        run: npm i
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRALDE_PUBLISH_KEY }}
          GRALDE_PUBLISH_SECRET: ${{ secrets.GRALDE_PUBLISH_SECRET }}
        run: npx semantic-release
